# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  NEON_DATABASE_USERNAME: ${{ secrets.PG_USERNAME }}
  NEON_DATABASE_NAME: ${{ secrets.PG_DATABASE }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sgn
      POSTMARK_SERVER_TOKEN: ${{ secrets.POSTMARK_SERVER_TOKEN }}
      MAIL_FROM: flavio@tekoa.tech
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      TEST_ACCOUNT_USER: ${{ secrets.TEST_ACCOUNT_USER }}
      TEST_ACCOUNT_PASSWORD: ${{ secrets.TEST_ACCOUNT_PASSWORD }}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sgn
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: npm install

      - name: Prepare DB
        run: npm run migrate

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          record: true
          wait-on: "http://localhost:3000"
